apiVersion: v1
kind: Namespace
metadata:
  name: temporal

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: temporal
spec:
  ports:
    - port: 9200
  selector:
    app: elasticsearch

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0   # Replace with desired version
          env:
            - name: discovery.type
              value: "single-node"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          ports:
            - containerPort: 9200

---

apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: temporal
spec:
  ports:
    - port: 5432
  selector:
    app: postgresql

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: "postgres:13" # Replace with desired version
          env:
            - name: POSTGRES_PASSWORD
              value: "temporal"
            - name: POSTGRES_USER
              value: "temporal"
          ports:
            - containerPort: 5432

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: "temporalio/auto-setup:1.7.0" # Replace with desired version
          env:
            - name: DB
              value: "postgresql"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "temporal"
            - name: POSTGRES_PWD
              value: "temporal"
            - name: POSTGRES_SEEDS
              value: "postgresql"
            - name: ENABLE_ES
              value: "true"
            - name: ES_SEEDS
              value: "elasticsearch"
            - name: ES_VERSION
              value: "v7"
          ports:
            - containerPort: 7233

---

apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: temporal
spec:
  type: NodePort
  ports:
    - port: 7233
      targetPort: 7233
      nodePort: 30733 # Optional: specify a node port; otherwise, one will be assigned automatically
  selector:
    app: temporal

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/web:1.12.0   # Replace with desired version
          env:
            - name: TEMPORAL_ADDRESS
              value: "temporal:7233"
            - name: TEMPORAL_CORS_ORIGINS
              value: "http://localhost:8088"
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: temporal
spec:
  type: NodePort
  ports:
    - port: 8088
      targetPort: 8088
      nodePort: 30808 # Optional: specify a node port; otherwise, one will be assigned automatically
  selector:
    app: temporal-ui
